/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-12-21T01:54:06+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequest,
  InternalException,
  LinkType,
  LinkTypeArray,
  LinkTypeSingle,
  LinkTypeUpdate,
  NotFound,
  TransactionArray,
  TransactionLinkArray,
  TransactionLinkSingle,
  TransactionLinkStore,
  TransactionLinkUpdate,
  TransactionTypeFilter,
  Unauthenticated,
  ValidationError,
} from '../models/index';
import {
    BadRequestFromJSON,
    BadRequestToJSON,
    InternalExceptionFromJSON,
    InternalExceptionToJSON,
    LinkTypeFromJSON,
    LinkTypeToJSON,
    LinkTypeArrayFromJSON,
    LinkTypeArrayToJSON,
    LinkTypeSingleFromJSON,
    LinkTypeSingleToJSON,
    LinkTypeUpdateFromJSON,
    LinkTypeUpdateToJSON,
    NotFoundFromJSON,
    NotFoundToJSON,
    TransactionArrayFromJSON,
    TransactionArrayToJSON,
    TransactionLinkArrayFromJSON,
    TransactionLinkArrayToJSON,
    TransactionLinkSingleFromJSON,
    TransactionLinkSingleToJSON,
    TransactionLinkStoreFromJSON,
    TransactionLinkStoreToJSON,
    TransactionLinkUpdateFromJSON,
    TransactionLinkUpdateToJSON,
    TransactionTypeFilterFromJSON,
    TransactionTypeFilterToJSON,
    UnauthenticatedFromJSON,
    UnauthenticatedToJSON,
    ValidationErrorFromJSON,
    ValidationErrorToJSON,
} from '../models/index';

export interface DeleteLinkTypeRequest {
    id: string;
    xTraceId?: string;
}

export interface DeleteTransactionLinkRequest {
    id: string;
    xTraceId?: string;
}

export interface GetLinkTypeRequest {
    id: string;
    xTraceId?: string;
}

export interface GetTransactionLinkRequest {
    id: string;
    xTraceId?: string;
}

export interface ListLinkTypeRequest {
    xTraceId?: string;
    limit?: number;
    page?: number;
}

export interface ListTransactionByLinkTypeRequest {
    id: string;
    xTraceId?: string;
    limit?: number;
    page?: number;
    start?: Date;
    end?: Date;
    type?: TransactionTypeFilter;
}

export interface ListTransactionLinkRequest {
    xTraceId?: string;
    limit?: number;
    page?: number;
}

export interface StoreLinkTypeRequest {
    linkType: LinkType;
    xTraceId?: string;
}

export interface StoreTransactionLinkRequest {
    transactionLinkStore: TransactionLinkStore;
    xTraceId?: string;
}

export interface UpdateLinkTypeRequest {
    id: string;
    linkTypeUpdate: LinkTypeUpdate;
    xTraceId?: string;
}

export interface UpdateTransactionLinkRequest {
    id: string;
    transactionLinkUpdate: TransactionLinkUpdate;
    xTraceId?: string;
}

/**
 * 
 */
export class LinksApi extends runtime.BaseAPI {

    /**
     * Will permanently delete a link type. The links between transactions will be removed. The transactions themselves remain. You cannot delete some of the system provided link types, indicated by the editable=false flag when you list it. 
     * Permanently delete link type.
     */
    async deleteLinkTypeRaw(requestParameters: DeleteLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteLinkType.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/link-types/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Will permanently delete a link type. The links between transactions will be removed. The transactions themselves remain. You cannot delete some of the system provided link types, indicated by the editable=false flag when you list it. 
     * Permanently delete link type.
     */
    async deleteLinkType(requestParameters: DeleteLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLinkTypeRaw(requestParameters, initOverrides);
    }

    /**
     * Will permanently delete link. Transactions remain. 
     * Permanently delete link between transactions.
     */
    async deleteTransactionLinkRaw(requestParameters: DeleteTransactionLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteTransactionLink.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/transaction-links/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Will permanently delete link. Transactions remain. 
     * Permanently delete link between transactions.
     */
    async deleteTransactionLink(requestParameters: DeleteTransactionLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTransactionLinkRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a single link type by its ID. 
     * Get single a link type.
     */
    async getLinkTypeRaw(requestParameters: GetLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LinkTypeSingle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getLinkType.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/link-types/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkTypeSingleFromJSON(jsonValue));
    }

    /**
     * Returns a single link type by its ID. 
     * Get single a link type.
     */
    async getLinkType(requestParameters: GetLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LinkTypeSingle> {
        const response = await this.getLinkTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a single link by its ID. 
     * Get a single link.
     */
    async getTransactionLinkRaw(requestParameters: GetTransactionLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionLinkSingle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getTransactionLink.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/transaction-links/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionLinkSingleFromJSON(jsonValue));
    }

    /**
     * Returns a single link by its ID. 
     * Get a single link.
     */
    async getTransactionLink(requestParameters: GetTransactionLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionLinkSingle> {
        const response = await this.getTransactionLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all the link types the system has. These include the default ones as well as any new ones. 
     * List all types of links.
     */
    async listLinkTypeRaw(requestParameters: ListLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LinkTypeArray>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/link-types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkTypeArrayFromJSON(jsonValue));
    }

    /**
     * List all the link types the system has. These include the default ones as well as any new ones. 
     * List all types of links.
     */
    async listLinkType(requestParameters: ListLinkTypeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LinkTypeArray> {
        const response = await this.listLinkTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all transactions under this link type, both the inward and outward transactions. 
     * List all transactions under this link type.
     */
    async listTransactionByLinkTypeRaw(requestParameters: ListTransactionByLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionArray>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling listTransactionByLinkType.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.start !== undefined) {
            queryParameters['start'] = (requestParameters.start as any).toISOString().substring(0,10);
        }

        if (requestParameters.end !== undefined) {
            queryParameters['end'] = (requestParameters.end as any).toISOString().substring(0,10);
        }

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/link-types/{id}/transactions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionArrayFromJSON(jsonValue));
    }

    /**
     * List all transactions under this link type, both the inward and outward transactions. 
     * List all transactions under this link type.
     */
    async listTransactionByLinkType(requestParameters: ListTransactionByLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionArray> {
        const response = await this.listTransactionByLinkTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all the transaction links. 
     * List all transaction links.
     */
    async listTransactionLinkRaw(requestParameters: ListTransactionLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionLinkArray>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/transaction-links`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionLinkArrayFromJSON(jsonValue));
    }

    /**
     * List all the transaction links. 
     * List all transaction links.
     */
    async listTransactionLink(requestParameters: ListTransactionLinkRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionLinkArray> {
        const response = await this.listTransactionLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new link type. The data required can be submitted as a JSON body or as a list of parameters (in key=value pairs, like a webform).
     * Create a new link type
     */
    async storeLinkTypeRaw(requestParameters: StoreLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LinkTypeSingle>> {
        if (requestParameters.linkType === null || requestParameters.linkType === undefined) {
            throw new runtime.RequiredError('linkType','Required parameter requestParameters.linkType was null or undefined when calling storeLinkType.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/link-types`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LinkTypeToJSON(requestParameters.linkType),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkTypeSingleFromJSON(jsonValue));
    }

    /**
     * Creates a new link type. The data required can be submitted as a JSON body or as a list of parameters (in key=value pairs, like a webform).
     * Create a new link type
     */
    async storeLinkType(requestParameters: StoreLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LinkTypeSingle> {
        const response = await this.storeLinkTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Store a new link between two transactions. For this end point you need the journal_id from a transaction.
     * Create a new link between transactions
     */
    async storeTransactionLinkRaw(requestParameters: StoreTransactionLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionLinkSingle>> {
        if (requestParameters.transactionLinkStore === null || requestParameters.transactionLinkStore === undefined) {
            throw new runtime.RequiredError('transactionLinkStore','Required parameter requestParameters.transactionLinkStore was null or undefined when calling storeTransactionLink.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/transaction-links`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionLinkStoreToJSON(requestParameters.transactionLinkStore),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionLinkSingleFromJSON(jsonValue));
    }

    /**
     * Store a new link between two transactions. For this end point you need the journal_id from a transaction.
     * Create a new link between transactions
     */
    async storeTransactionLink(requestParameters: StoreTransactionLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionLinkSingle> {
        const response = await this.storeTransactionLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Used to update a single link type. All fields that are not submitted will be cleared (set to NULL). The model will tell you which fields are mandatory. You cannot update some of the system provided link types, indicated by the editable=false flag when you list it. 
     * Update existing link type.
     */
    async updateLinkTypeRaw(requestParameters: UpdateLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LinkTypeSingle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateLinkType.');
        }

        if (requestParameters.linkTypeUpdate === null || requestParameters.linkTypeUpdate === undefined) {
            throw new runtime.RequiredError('linkTypeUpdate','Required parameter requestParameters.linkTypeUpdate was null or undefined when calling updateLinkType.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/link-types/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LinkTypeUpdateToJSON(requestParameters.linkTypeUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkTypeSingleFromJSON(jsonValue));
    }

    /**
     * Used to update a single link type. All fields that are not submitted will be cleared (set to NULL). The model will tell you which fields are mandatory. You cannot update some of the system provided link types, indicated by the editable=false flag when you list it. 
     * Update existing link type.
     */
    async updateLinkType(requestParameters: UpdateLinkTypeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LinkTypeSingle> {
        const response = await this.updateLinkTypeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Used to update a single existing link. 
     * Update an existing link between transactions.
     */
    async updateTransactionLinkRaw(requestParameters: UpdateTransactionLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionLinkSingle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateTransactionLink.');
        }

        if (requestParameters.transactionLinkUpdate === null || requestParameters.transactionLinkUpdate === undefined) {
            throw new runtime.RequiredError('transactionLinkUpdate','Required parameter requestParameters.transactionLinkUpdate was null or undefined when calling updateTransactionLink.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/transaction-links/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TransactionLinkUpdateToJSON(requestParameters.transactionLinkUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionLinkSingleFromJSON(jsonValue));
    }

    /**
     * Used to update a single existing link. 
     * Update an existing link between transactions.
     */
    async updateTransactionLink(requestParameters: UpdateTransactionLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionLinkSingle> {
        const response = await this.updateTransactionLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
