/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-10-15T12:13:25+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequest,
  BillArray,
  InternalException,
  NotFound,
  ObjectGroupArray,
  ObjectGroupSingle,
  ObjectGroupUpdate,
  PiggyBankArray,
  Unauthenticated,
  ValidationError,
} from '../models/index';
import {
    BadRequestFromJSON,
    BadRequestToJSON,
    BillArrayFromJSON,
    BillArrayToJSON,
    InternalExceptionFromJSON,
    InternalExceptionToJSON,
    NotFoundFromJSON,
    NotFoundToJSON,
    ObjectGroupArrayFromJSON,
    ObjectGroupArrayToJSON,
    ObjectGroupSingleFromJSON,
    ObjectGroupSingleToJSON,
    ObjectGroupUpdateFromJSON,
    ObjectGroupUpdateToJSON,
    PiggyBankArrayFromJSON,
    PiggyBankArrayToJSON,
    UnauthenticatedFromJSON,
    UnauthenticatedToJSON,
    ValidationErrorFromJSON,
    ValidationErrorToJSON,
} from '../models/index';

export interface DeleteObjectGroupRequest {
    id: string;
    xTraceId?: string;
}

export interface GetObjectGroupRequest {
    id: string;
    xTraceId?: string;
}

export interface ListBillByObjectGroupRequest {
    id: string;
    xTraceId?: string;
    limit?: number;
    page?: number;
}

export interface ListObjectGroupsRequest {
    xTraceId?: string;
    limit?: number;
    page?: number;
}

export interface ListPiggyBankByObjectGroupRequest {
    id: string;
    xTraceId?: string;
    limit?: number;
    page?: number;
}

export interface UpdateObjectGroupRequest {
    id: string;
    objectGroupUpdate: ObjectGroupUpdate;
    xTraceId?: string;
}

/**
 * 
 */
export class ObjectGroupsApi extends runtime.BaseAPI {

    /**
     * Delete a object group.
     * Delete a object group.
     */
    async deleteObjectGroupRaw(requestParameters: DeleteObjectGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteObjectGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/object-groups/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a object group.
     * Delete a object group.
     */
    async deleteObjectGroup(requestParameters: DeleteObjectGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteObjectGroupRaw(requestParameters, initOverrides);
    }

    /**
     * Get a single object group.
     * Get a single object group.
     */
    async getObjectGroupRaw(requestParameters: GetObjectGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectGroupSingle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getObjectGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/object-groups/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectGroupSingleFromJSON(jsonValue));
    }

    /**
     * Get a single object group.
     * Get a single object group.
     */
    async getObjectGroup(requestParameters: GetObjectGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectGroupSingle> {
        const response = await this.getObjectGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all bills with this object group.
     * List all bills with this object group.
     */
    async listBillByObjectGroupRaw(requestParameters: ListBillByObjectGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BillArray>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling listBillByObjectGroup.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/object-groups/{id}/bills`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BillArrayFromJSON(jsonValue));
    }

    /**
     * List all bills with this object group.
     * List all bills with this object group.
     */
    async listBillByObjectGroup(requestParameters: ListBillByObjectGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BillArray> {
        const response = await this.listBillByObjectGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all oject groups.
     * List all oject groups.
     */
    async listObjectGroupsRaw(requestParameters: ListObjectGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectGroupArray>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/object-groups`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectGroupArrayFromJSON(jsonValue));
    }

    /**
     * List all oject groups.
     * List all oject groups.
     */
    async listObjectGroups(requestParameters: ListObjectGroupsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectGroupArray> {
        const response = await this.listObjectGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint returns a list of all the piggy banks connected to the object group. 
     * List all piggy banks related to the object group.
     */
    async listPiggyBankByObjectGroupRaw(requestParameters: ListPiggyBankByObjectGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PiggyBankArray>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling listPiggyBankByObjectGroup.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/object-groups/{id}/piggy-banks`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PiggyBankArrayFromJSON(jsonValue));
    }

    /**
     * This endpoint returns a list of all the piggy banks connected to the object group. 
     * List all piggy banks related to the object group.
     */
    async listPiggyBankByObjectGroup(requestParameters: ListPiggyBankByObjectGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PiggyBankArray> {
        const response = await this.listPiggyBankByObjectGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update existing object group.
     * Update existing object group.
     */
    async updateObjectGroupRaw(requestParameters: UpdateObjectGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectGroupSingle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateObjectGroup.');
        }

        if (requestParameters.objectGroupUpdate === null || requestParameters.objectGroupUpdate === undefined) {
            throw new runtime.RequiredError('objectGroupUpdate','Required parameter requestParameters.objectGroupUpdate was null or undefined when calling updateObjectGroup.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters.xTraceId !== undefined && requestParameters.xTraceId !== null) {
            headerParameters['X-Trace-Id'] = String(requestParameters.xTraceId);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("firefly_iii_auth", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("local_bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/object-groups/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ObjectGroupUpdateToJSON(requestParameters.objectGroupUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectGroupSingleFromJSON(jsonValue));
    }

    /**
     * Update existing object group.
     * Update existing object group.
     */
    async updateObjectGroup(requestParameters: UpdateObjectGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectGroupSingle> {
        const response = await this.updateObjectGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
