/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-10-15T12:13:25+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountRead } from './AccountRead';
import {
    AccountReadFromJSON,
    AccountReadFromJSONTyped,
    AccountReadToJSON,
} from './AccountRead';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
} from './Meta';

/**
 * 
 * @export
 * @interface AccountArray
 */
export interface AccountArray {
    /**
     * 
     * @type {Array<AccountRead>}
     * @memberof AccountArray
     */
    data: Array<AccountRead>;
    /**
     * 
     * @type {Meta}
     * @memberof AccountArray
     */
    meta: Meta;
}

/**
 * Check if a given object implements the AccountArray interface.
 */
export function instanceOfAccountArray(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;

    return isInstance;
}

export function AccountArrayFromJSON(json: any): AccountArray {
    return AccountArrayFromJSONTyped(json, false);
}

export function AccountArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AccountReadFromJSON)),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function AccountArrayToJSON(value?: AccountArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AccountReadToJSON)),
        'meta': MetaToJSON(value.meta),
    };
}

