/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-10-15T12:13:25+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The object class to which the attachment must be linked.
 * @export
 */
export const AttachableType = {
    Account: 'Account',
    Budget: 'Budget',
    Bill: 'Bill',
    TransactionJournal: 'TransactionJournal',
    PiggyBank: 'PiggyBank',
    Tag: 'Tag'
} as const;
export type AttachableType = typeof AttachableType[keyof typeof AttachableType];


export function AttachableTypeFromJSON(json: any): AttachableType {
    return AttachableTypeFromJSONTyped(json, false);
}

export function AttachableTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachableType {
    return json as AttachableType;
}

export function AttachableTypeToJSON(value?: AttachableType | null): any {
    return value as any;
}

