/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-12-21T01:54:06+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteTransactionType
 */
export interface AutocompleteTransactionType {
    /**
     * 
     * @type {string}
     * @memberof AutocompleteTransactionType
     */
    id: string;
    /**
     * Type of the object found by an auto-complete search.
     * @type {string}
     * @memberof AutocompleteTransactionType
     */
    name: string;
    /**
     * Name of the object found by an auto-complete search.
     * @type {string}
     * @memberof AutocompleteTransactionType
     */
    type: string;
}

/**
 * Check if a given object implements the AutocompleteTransactionType interface.
 */
export function instanceOfAutocompleteTransactionType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function AutocompleteTransactionTypeFromJSON(json: any): AutocompleteTransactionType {
    return AutocompleteTransactionTypeFromJSONTyped(json, false);
}

export function AutocompleteTransactionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteTransactionType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
    };
}

export function AutocompleteTransactionTypeToJSON(value?: AutocompleteTransactionType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': value.type,
    };
}

