/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-10-15T12:13:25+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteAccount
 */
export interface AutocompleteAccount {
    /**
     * 
     * @type {string}
     * @memberof AutocompleteAccount
     */
    id: string;
    /**
     * Name of the account found by an auto-complete search.
     * @type {string}
     * @memberof AutocompleteAccount
     */
    name: string;
    /**
     * Asset accounts and liabilities have a second field with the given date's account balance.
     * @type {string}
     * @memberof AutocompleteAccount
     */
    nameWithBalance: string;
    /**
     * Account type of the account found by the auto-complete search.
     * @type {string}
     * @memberof AutocompleteAccount
     */
    type: string;
    /**
     * ID for the currency used by this account.
     * @type {string}
     * @memberof AutocompleteAccount
     */
    currencyId: string;
    /**
     * Currency name for the currency used by this account.
     * @type {string}
     * @memberof AutocompleteAccount
     */
    currencyName: string;
    /**
     * Currency code for the currency used by this account.
     * @type {string}
     * @memberof AutocompleteAccount
     */
    currencyCode: string;
    /**
     * Currency symbol for the currency used by this account.
     * @type {string}
     * @memberof AutocompleteAccount
     */
    currencySymbol: string;
    /**
     * Number of decimal places for the currency used by this account.
     * @type {number}
     * @memberof AutocompleteAccount
     */
    currencyDecimalPlaces: number;
}

/**
 * Check if a given object implements the AutocompleteAccount interface.
 */
export function instanceOfAutocompleteAccount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "nameWithBalance" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "currencyId" in value;
    isInstance = isInstance && "currencyName" in value;
    isInstance = isInstance && "currencyCode" in value;
    isInstance = isInstance && "currencySymbol" in value;
    isInstance = isInstance && "currencyDecimalPlaces" in value;

    return isInstance;
}

export function AutocompleteAccountFromJSON(json: any): AutocompleteAccount {
    return AutocompleteAccountFromJSONTyped(json, false);
}

export function AutocompleteAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'nameWithBalance': json['name_with_balance'],
        'type': json['type'],
        'currencyId': json['currency_id'],
        'currencyName': json['currency_name'],
        'currencyCode': json['currency_code'],
        'currencySymbol': json['currency_symbol'],
        'currencyDecimalPlaces': json['currency_decimal_places'],
    };
}

export function AutocompleteAccountToJSON(value?: AutocompleteAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'name_with_balance': value.nameWithBalance,
        'type': value.type,
        'currency_id': value.currencyId,
        'currency_name': value.currencyName,
        'currency_code': value.currencyCode,
        'currency_symbol': value.currencySymbol,
        'currency_decimal_places': value.currencyDecimalPlaces,
    };
}

