/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-10-15T12:13:25+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Budget } from './Budget';
import {
    BudgetFromJSON,
    BudgetFromJSONTyped,
    BudgetToJSON,
} from './Budget';

/**
 * 
 * @export
 * @interface BudgetRead
 */
export interface BudgetRead {
    /**
     * Immutable value
     * @type {string}
     * @memberof BudgetRead
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof BudgetRead
     */
    id: string;
    /**
     * 
     * @type {Budget}
     * @memberof BudgetRead
     */
    attributes: Budget;
}

/**
 * Check if a given object implements the BudgetRead interface.
 */
export function instanceOfBudgetRead(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function BudgetReadFromJSON(json: any): BudgetRead {
    return BudgetReadFromJSONTyped(json, false);
}

export function BudgetReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': BudgetFromJSON(json['attributes']),
    };
}

export function BudgetReadToJSON(value?: BudgetRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': BudgetToJSON(value.attributes),
    };
}

