/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-10-15T12:13:25+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BudgetLimitRead } from './BudgetLimitRead';
import {
    BudgetLimitReadFromJSON,
    BudgetLimitReadFromJSONTyped,
    BudgetLimitReadToJSON,
} from './BudgetLimitRead';

/**
 * 
 * @export
 * @interface BudgetLimitSingle
 */
export interface BudgetLimitSingle {
    /**
     * 
     * @type {BudgetLimitRead}
     * @memberof BudgetLimitSingle
     */
    data: BudgetLimitRead;
}

/**
 * Check if a given object implements the BudgetLimitSingle interface.
 */
export function instanceOfBudgetLimitSingle(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function BudgetLimitSingleFromJSON(json: any): BudgetLimitSingle {
    return BudgetLimitSingleFromJSONTyped(json, false);
}

export function BudgetLimitSingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): BudgetLimitSingle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': BudgetLimitReadFromJSON(json['data']),
    };
}

export function BudgetLimitSingleToJSON(value?: BudgetLimitSingle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': BudgetLimitReadToJSON(value.data),
    };
}

