/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-12-21T01:54:06+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoryRead } from './CategoryRead';
import {
    CategoryReadFromJSON,
    CategoryReadFromJSONTyped,
    CategoryReadToJSON,
} from './CategoryRead';

/**
 * 
 * @export
 * @interface CategorySingle
 */
export interface CategorySingle {
    /**
     * 
     * @type {CategoryRead}
     * @memberof CategorySingle
     */
    data: CategoryRead;
}

/**
 * Check if a given object implements the CategorySingle interface.
 */
export function instanceOfCategorySingle(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CategorySingleFromJSON(json: any): CategorySingle {
    return CategorySingleFromJSONTyped(json, false);
}

export function CategorySingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategorySingle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CategoryReadFromJSON(json['data']),
    };
}

export function CategorySingleToJSON(value?: CategorySingle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CategoryReadToJSON(value.data),
    };
}

