/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-10-15T12:13:25+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CronResultRow } from './CronResultRow';
import {
    CronResultRowFromJSON,
    CronResultRowFromJSONTyped,
    CronResultRowToJSON,
} from './CronResultRow';

/**
 * 
 * @export
 * @interface CronResult
 */
export interface CronResult {
    /**
     * 
     * @type {CronResultRow}
     * @memberof CronResult
     */
    recurringTransactions?: CronResultRow;
    /**
     * 
     * @type {CronResultRow}
     * @memberof CronResult
     */
    autoBudgets?: CronResultRow;
    /**
     * 
     * @type {CronResultRow}
     * @memberof CronResult
     */
    telemetry?: CronResultRow;
}

/**
 * Check if a given object implements the CronResult interface.
 */
export function instanceOfCronResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CronResultFromJSON(json: any): CronResult {
    return CronResultFromJSONTyped(json, false);
}

export function CronResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CronResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recurringTransactions': !exists(json, 'recurring_transactions') ? undefined : CronResultRowFromJSON(json['recurring_transactions']),
        'autoBudgets': !exists(json, 'auto_budgets') ? undefined : CronResultRowFromJSON(json['auto_budgets']),
        'telemetry': !exists(json, 'telemetry') ? undefined : CronResultRowFromJSON(json['telemetry']),
    };
}

export function CronResultToJSON(value?: CronResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recurring_transactions': CronResultRowToJSON(value.recurringTransactions),
        'auto_budgets': CronResultRowToJSON(value.autoBudgets),
        'telemetry': CronResultRowToJSON(value.telemetry),
    };
}

