/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-12-21T01:54:06+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CurrencyRead } from './CurrencyRead';
import {
    CurrencyReadFromJSON,
    CurrencyReadFromJSONTyped,
    CurrencyReadToJSON,
} from './CurrencyRead';

/**
 * 
 * @export
 * @interface CurrencySingle
 */
export interface CurrencySingle {
    /**
     * 
     * @type {CurrencyRead}
     * @memberof CurrencySingle
     */
    data: CurrencyRead;
}

/**
 * Check if a given object implements the CurrencySingle interface.
 */
export function instanceOfCurrencySingle(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CurrencySingleFromJSON(json: any): CurrencySingle {
    return CurrencySingleFromJSONTyped(json, false);
}

export function CurrencySingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencySingle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CurrencyReadFromJSON(json['data']),
    };
}

export function CurrencySingleToJSON(value?: CurrencySingle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CurrencyReadToJSON(value.data),
    };
}

