/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-12-21T01:54:06+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Currency
 */
export interface Currency {
    /**
     * 
     * @type {Date}
     * @memberof Currency
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Currency
     */
    readonly updatedAt?: Date;
    /**
     * Defaults to true
     * @type {boolean}
     * @memberof Currency
     */
    enabled?: boolean;
    /**
     * Make this currency the default currency.
     * @type {boolean}
     * @memberof Currency
     */
    _default?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    symbol: string;
    /**
     * Supports 0-16 decimals.
     * @type {number}
     * @memberof Currency
     */
    decimalPlaces?: number;
}

/**
 * Check if a given object implements the Currency interface.
 */
export function instanceOfCurrency(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "symbol" in value;

    return isInstance;
}

export function CurrencyFromJSON(json: any): Currency {
    return CurrencyFromJSONTyped(json, false);
}

export function CurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Currency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        '_default': !exists(json, 'default') ? undefined : json['default'],
        'code': json['code'],
        'name': json['name'],
        'symbol': json['symbol'],
        'decimalPlaces': !exists(json, 'decimal_places') ? undefined : json['decimal_places'],
    };
}

export function CurrencyToJSON(value?: Currency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'default': value._default,
        'code': value.code,
        'name': value.name,
        'symbol': value.symbol,
        'decimal_places': value.decimalPlaces,
    };
}

