/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-10-15T12:13:25+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrencyStore
 */
export interface CurrencyStore {
    /**
     * Defaults to true
     * @type {boolean}
     * @memberof CurrencyStore
     */
    enabled?: boolean;
    /**
     * Make this currency the default currency.
     * @type {boolean}
     * @memberof CurrencyStore
     */
    _default?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CurrencyStore
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CurrencyStore
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CurrencyStore
     */
    symbol: string;
    /**
     * Supports 0-16 decimals.
     * @type {number}
     * @memberof CurrencyStore
     */
    decimalPlaces?: number;
}

/**
 * Check if a given object implements the CurrencyStore interface.
 */
export function instanceOfCurrencyStore(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "symbol" in value;

    return isInstance;
}

export function CurrencyStoreFromJSON(json: any): CurrencyStore {
    return CurrencyStoreFromJSONTyped(json, false);
}

export function CurrencyStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyStore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        '_default': !exists(json, 'default') ? undefined : json['default'],
        'code': json['code'],
        'name': json['name'],
        'symbol': json['symbol'],
        'decimalPlaces': !exists(json, 'decimal_places') ? undefined : json['decimal_places'],
    };
}

export function CurrencyStoreToJSON(value?: CurrencyStore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'default': value._default,
        'code': value.code,
        'name': value.name,
        'symbol': value.symbol,
        'decimal_places': value.decimalPlaces,
    };
}

