/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-12-21T01:54:06+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetaPagination
 */
export interface MetaPagination {
    /**
     * 
     * @type {number}
     * @memberof MetaPagination
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaPagination
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaPagination
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaPagination
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaPagination
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the MetaPagination interface.
 */
export function instanceOfMetaPagination(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MetaPaginationFromJSON(json: any): MetaPagination {
    return MetaPaginationFromJSONTyped(json, false);
}

export function MetaPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaPagination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': !exists(json, 'total') ? undefined : json['total'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'perPage': !exists(json, 'per_page') ? undefined : json['per_page'],
        'currentPage': !exists(json, 'current_page') ? undefined : json['current_page'],
        'totalPages': !exists(json, 'total_pages') ? undefined : json['total_pages'],
    };
}

export function MetaPaginationToJSON(value?: MetaPagination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'count': value.count,
        'per_page': value.perPage,
        'current_page': value.currentPage,
        'total_pages': value.totalPages,
    };
}

