/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-10-15T12:13:25+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
} from './Meta';
import type { ObjectGroupRead } from './ObjectGroupRead';
import {
    ObjectGroupReadFromJSON,
    ObjectGroupReadFromJSONTyped,
    ObjectGroupReadToJSON,
} from './ObjectGroupRead';

/**
 * 
 * @export
 * @interface ObjectGroupArray
 */
export interface ObjectGroupArray {
    /**
     * 
     * @type {Array<ObjectGroupRead>}
     * @memberof ObjectGroupArray
     */
    data: Array<ObjectGroupRead>;
    /**
     * 
     * @type {Meta}
     * @memberof ObjectGroupArray
     */
    meta: Meta;
}

/**
 * Check if a given object implements the ObjectGroupArray interface.
 */
export function instanceOfObjectGroupArray(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;

    return isInstance;
}

export function ObjectGroupArrayFromJSON(json: any): ObjectGroupArray {
    return ObjectGroupArrayFromJSONTyped(json, false);
}

export function ObjectGroupArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectGroupArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ObjectGroupReadFromJSON)),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function ObjectGroupArrayToJSON(value?: ObjectGroupArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ObjectGroupReadToJSON)),
        'meta': MetaToJSON(value.meta),
    };
}

