/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-12-21T01:54:06+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
} from './Meta';
import type { PageLink } from './PageLink';
import {
    PageLinkFromJSON,
    PageLinkFromJSONTyped,
    PageLinkToJSON,
} from './PageLink';
import type { PreferenceRead } from './PreferenceRead';
import {
    PreferenceReadFromJSON,
    PreferenceReadFromJSONTyped,
    PreferenceReadToJSON,
} from './PreferenceRead';

/**
 * 
 * @export
 * @interface PreferenceArray
 */
export interface PreferenceArray {
    /**
     * 
     * @type {Array<PreferenceRead>}
     * @memberof PreferenceArray
     */
    data: Array<PreferenceRead>;
    /**
     * 
     * @type {Meta}
     * @memberof PreferenceArray
     */
    meta: Meta;
    /**
     * 
     * @type {PageLink}
     * @memberof PreferenceArray
     */
    links: PageLink;
}

/**
 * Check if a given object implements the PreferenceArray interface.
 */
export function instanceOfPreferenceArray(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function PreferenceArrayFromJSON(json: any): PreferenceArray {
    return PreferenceArrayFromJSONTyped(json, false);
}

export function PreferenceArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferenceArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PreferenceReadFromJSON)),
        'meta': MetaFromJSON(json['meta']),
        'links': PageLinkFromJSON(json['links']),
    };
}

export function PreferenceArrayToJSON(value?: PreferenceArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(PreferenceReadToJSON)),
        'meta': MetaToJSON(value.meta),
        'links': PageLinkToJSON(value.links),
    };
}

