/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-12-21T01:54:06+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RecurrenceRepetition } from './RecurrenceRepetition';
import {
    RecurrenceRepetitionFromJSON,
    RecurrenceRepetitionFromJSONTyped,
    RecurrenceRepetitionToJSON,
} from './RecurrenceRepetition';
import type { RecurrenceTransaction } from './RecurrenceTransaction';
import {
    RecurrenceTransactionFromJSON,
    RecurrenceTransactionFromJSONTyped,
    RecurrenceTransactionToJSON,
} from './RecurrenceTransaction';
import type { RecurrenceTransactionType } from './RecurrenceTransactionType';
import {
    RecurrenceTransactionTypeFromJSON,
    RecurrenceTransactionTypeFromJSONTyped,
    RecurrenceTransactionTypeToJSON,
} from './RecurrenceTransactionType';

/**
 * 
 * @export
 * @interface Recurrence
 */
export interface Recurrence {
    /**
     * 
     * @type {Date}
     * @memberof Recurrence
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Recurrence
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {RecurrenceTransactionType}
     * @memberof Recurrence
     */
    type?: RecurrenceTransactionType;
    /**
     * 
     * @type {string}
     * @memberof Recurrence
     */
    title?: string;
    /**
     * Not to be confused with the description of the actual transaction(s) being created.
     * @type {string}
     * @memberof Recurrence
     */
    description?: string;
    /**
     * First time the recurring transaction will fire. Must be after today.
     * @type {Date}
     * @memberof Recurrence
     */
    firstDate?: Date;
    /**
     * Last time the recurring transaction has fired.
     * @type {Date}
     * @memberof Recurrence
     */
    readonly latestDate?: Date | null;
    /**
     * Date until the recurring transaction can fire. Use either this field or repetitions.
     * @type {Date}
     * @memberof Recurrence
     */
    repeatUntil?: Date | null;
    /**
     * Max number of created transactions. Use either this field or repeat_until.
     * @type {number}
     * @memberof Recurrence
     */
    nrOfRepetitions?: number | null;
    /**
     * Whether or not to fire the rules after the creation of a transaction.
     * @type {boolean}
     * @memberof Recurrence
     */
    applyRules?: boolean;
    /**
     * If the recurrence is even active.
     * @type {boolean}
     * @memberof Recurrence
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Recurrence
     */
    notes?: string | null;
    /**
     * 
     * @type {Array<RecurrenceRepetition>}
     * @memberof Recurrence
     */
    repetitions?: Array<RecurrenceRepetition>;
    /**
     * 
     * @type {Array<RecurrenceTransaction>}
     * @memberof Recurrence
     */
    transactions?: Array<RecurrenceTransaction>;
}

/**
 * Check if a given object implements the Recurrence interface.
 */
export function instanceOfRecurrence(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecurrenceFromJSON(json: any): Recurrence {
    return RecurrenceFromJSONTyped(json, false);
}

export function RecurrenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recurrence {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'type': !exists(json, 'type') ? undefined : RecurrenceTransactionTypeFromJSON(json['type']),
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'firstDate': !exists(json, 'first_date') ? undefined : (new Date(json['first_date'])),
        'latestDate': !exists(json, 'latest_date') ? undefined : (json['latest_date'] === null ? null : new Date(json['latest_date'])),
        'repeatUntil': !exists(json, 'repeat_until') ? undefined : (json['repeat_until'] === null ? null : new Date(json['repeat_until'])),
        'nrOfRepetitions': !exists(json, 'nr_of_repetitions') ? undefined : json['nr_of_repetitions'],
        'applyRules': !exists(json, 'apply_rules') ? undefined : json['apply_rules'],
        'active': !exists(json, 'active') ? undefined : json['active'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'repetitions': !exists(json, 'repetitions') ? undefined : ((json['repetitions'] as Array<any>).map(RecurrenceRepetitionFromJSON)),
        'transactions': !exists(json, 'transactions') ? undefined : ((json['transactions'] as Array<any>).map(RecurrenceTransactionFromJSON)),
    };
}

export function RecurrenceToJSON(value?: Recurrence | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': RecurrenceTransactionTypeToJSON(value.type),
        'title': value.title,
        'description': value.description,
        'first_date': value.firstDate === undefined ? undefined : (value.firstDate.toISOString().substring(0,10)),
        'repeat_until': value.repeatUntil === undefined ? undefined : (value.repeatUntil === null ? null : value.repeatUntil.toISOString().substring(0,10)),
        'nr_of_repetitions': value.nrOfRepetitions,
        'apply_rules': value.applyRules,
        'active': value.active,
        'notes': value.notes,
        'repetitions': value.repetitions === undefined ? undefined : ((value.repetitions as Array<any>).map(RecurrenceRepetitionToJSON)),
        'transactions': value.transactions === undefined ? undefined : ((value.transactions as Array<any>).map(RecurrenceTransactionToJSON)),
    };
}

