/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-12-21T01:54:06+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
} from './Meta';
import type { PageLink } from './PageLink';
import {
    PageLinkFromJSON,
    PageLinkFromJSONTyped,
    PageLinkToJSON,
} from './PageLink';
import type { RecurrenceRead } from './RecurrenceRead';
import {
    RecurrenceReadFromJSON,
    RecurrenceReadFromJSONTyped,
    RecurrenceReadToJSON,
} from './RecurrenceRead';

/**
 * 
 * @export
 * @interface RecurrenceArray
 */
export interface RecurrenceArray {
    /**
     * 
     * @type {Array<RecurrenceRead>}
     * @memberof RecurrenceArray
     */
    data: Array<RecurrenceRead>;
    /**
     * 
     * @type {Meta}
     * @memberof RecurrenceArray
     */
    meta: Meta;
    /**
     * 
     * @type {PageLink}
     * @memberof RecurrenceArray
     */
    links: PageLink;
}

/**
 * Check if a given object implements the RecurrenceArray interface.
 */
export function instanceOfRecurrenceArray(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "meta" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function RecurrenceArrayFromJSON(json: any): RecurrenceArray {
    return RecurrenceArrayFromJSONTyped(json, false);
}

export function RecurrenceArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurrenceArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(RecurrenceReadFromJSON)),
        'meta': MetaFromJSON(json['meta']),
        'links': PageLinkFromJSON(json['links']),
    };
}

export function RecurrenceArrayToJSON(value?: RecurrenceArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(RecurrenceReadToJSON)),
        'meta': MetaToJSON(value.meta),
        'links': PageLinkToJSON(value.links),
    };
}

