/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v2.0.10
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-10-15T12:13:25+00:00  Please keep in mind that the demo site does not accept requests from curl, colly, wget, etc. You must use a browser or a tool like Postman to make requests. Too many script kiddies out there, sorry about that. 
 *
 * The version of the OpenAPI document: 2.0.10
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RuleRead } from './RuleRead';
import {
    RuleReadFromJSON,
    RuleReadFromJSONTyped,
    RuleReadToJSON,
} from './RuleRead';

/**
 * 
 * @export
 * @interface RuleSingle
 */
export interface RuleSingle {
    /**
     * 
     * @type {RuleRead}
     * @memberof RuleSingle
     */
    data: RuleRead;
}

/**
 * Check if a given object implements the RuleSingle interface.
 */
export function instanceOfRuleSingle(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function RuleSingleFromJSON(json: any): RuleSingle {
    return RuleSingleFromJSONTyped(json, false);
}

export function RuleSingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleSingle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': RuleReadFromJSON(json['data']),
    };
}

export function RuleSingleToJSON(value?: RuleSingle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': RuleReadToJSON(value.data),
    };
}

